/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
    /*
package leetcodeprob;

public class FindTheDifference {
    public static void main(String[] args) {
        String t="y";
        String s="";
        

        int result=0;
                 for(int i=0;i<t.length();i++) {
            result=result+t.toCharArray()[i];
        }

        for(int j=0;j<s.length();j++) {
            result=result-s.toCharArray()[j];
        }

        char ele = (char) result;
        System.out.println("Added character: " + ele);
    }
}
